# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPU_TYPE', models.CharField(default=b'none', max_length=100, verbose_name=b'CPU type')),
                ('CPU_CORE', models.IntegerField(verbose_name=b'CPU cores')),
                ('CPU_SPEED', models.FloatField(verbose_name=b'CPU speed(GB)')),
            ],
        ),
        migrations.RenameField(
            model_name='hd',
            old_name='question',
            new_name='HD_NIC_CPU',
        ),
        migrations.RemoveField(
            model_name='hd',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='hd',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='question_text',
        ),
        migrations.AddField(
            model_name='hd',
            name='HD_CAP',
            field=models.CharField(default=b'none', max_length=100, verbose_name=b'HD capacity'),
        ),
        migrations.AddField(
            model_name='hd',
            name='HD_ID',
            field=models.CharField(default=b'none', max_length=100, verbose_name=b'id num'),
        ),
        migrations.AddField(
            model_name='hd',
            name='HD_TYPE',
            field=models.CharField(default=b'none', max_length=100, verbose_name=b'HD type'),
        ),
        migrations.AddField(
            model_name='nic',
            name='NIC_CAP',
            field=models.CharField(default=b'none', max_length=100, verbose_name=b'NIC capabilities'),
        ),
        migrations.AddField(
            model_name='nic',
            name='NIC_MAC',
            field=models.CharField(default=b'none', max_length=100, verbose_name=b'MAC ADDR'),
        ),
        migrations.AddField(
            model_name='nic',
            name='NIC_TYPE',
            field=models.CharField(default=b'none', max_length=100, verbose_name=b'NIC TYPE'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='HD_NIC_CPU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appserver.NIC'),
        ),
    ]
